funds:
  - code: "140327"
    name: "Edelweiss Emerging Markets Opportunities Equity Offshore Fund Direct Growth"
  - code: "140243"
    name: "Edelweiss Greater China Equity Offshore Fund Direct Growth"
  - code: "118559"
    name: "Franklin Asian Equity Fund Direct Growth"
  - code: "148063"
    name: "Edelweiss US Technology Equity FoF Direct Growth"
  - code: "140296"
    name: "Edelweiss Europe Dynamic Equity Offshore Fund Direct Growth"
  - code: "140274"
    name: "Edelweiss US Value Equity Offshore Fund Direct Growth"
  - code: "118551"
    name: "Franklin U.S. Opportunities Equity Active FoF Direct Growth"
  - code: "140256"
    name: "Edelweiss ASEAN Equity Offshore Fund Direct Growth"
