funds:
  - code: "127042"
    name: "Motilal Oswal Midcap Fund-Direct Plan-Growth Option"
  - code: "118989"
    name: "HDFC Mid Cap Fund Direct Growth"
  - code: "118668"
    name: "Nippon India Growth Mid Cap Fund Direct Growth"
  - code: "150584"
    name: "WhiteOak Capital Mid Cap Fund Direct Growth"
  - code: "140228"
    name: "Edelweiss Mid Cap Direct Plan Growth"
  - code: "120403"
    name: "Invesco India Mid Cap Fund Direct Growth"
  - code: "151036"
    name: "HSBC Midcap Fund Direct Growth"
  - code: "120381"
    name: "ICICI Prudential Midcap Direct Plan Growth"

