funds:
  - code: "149383"
    name: "Axis Multicap Fund - Direct Growth"
  - code: "151443"
    name: "Bank of India Multi Cap Fund - Direct Growth"
  - code: "120599"
    name: "ICICI Prudential Multicap Fund - Direct Growth"
  - code: "149185"
    name: "Kotak Multicap Fund - Direct Growth"
  - code: "151290"
    name: "HSBC Multi Cap Fund - Direct Growth"
  - code: "141226"
    name: "Mahindra Manulife Multi Cap Fund - Direct Growth"
